# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=160)),
                ('sleep_cycle', models.CharField(choices=[('8pm - 4am', '4-19'), ('9pm - 5am', '5-20'), ('10pm - 6am', '6-21'), ('11pm - 7am', '7-22'), ('12pm - 8am', '8-23')], default='8pm - 4am', help_text='Assuming 8 hours sleep cycle', max_length=5)),
                ('every', models.CharField(choices=[('15 minutes', '15'), ('30 minutes', '30'), ('45 minutes', '45'), ('60 minutes', '0')], default='60 minutes', help_text='Repeat every', max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('celery_task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='django_celery_beat.PeriodicTask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
