# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_task_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='every',
            field=models.CharField(choices=[('*', 'every minute'), ('*/15', '15 minutes'), ('*/30', '30 minutes'), ('0', '60 minutes')], default='0', help_text='Repeat every', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='sleep_cycle',
            field=models.CharField(choices=[('4-19', '8pm - 4am'), ('5-20', '9pm - 5am'), ('6-21', '10pm - 6am'), ('7-22', '11pm - 7am'), ('8-23', '12am - 8am')], default='4-19', help_text='Assuming 8 hours sleep cycle. No messages will be sent during sleep cycle.', max_length=5),
        ),
    ]
