# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20170505_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='every',
            field=models.CharField(choices=[('*', 'every minute'), ('*/15', '15 minutes'), ('*/30', '30 minutes'), ('0', '60 minutes (hour)')], default='0', help_text='Repeat every', max_length=4),
        ),
    ]
