# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170504_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_tasks_created',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
